### ISSUE TITLE
Better error messages when book and examples are out of sync.

### ISSUE THREAD

**Issue by lukeyeh** [google/wasefire#444]
Noticed this while trying to run `scripts/ci.sh` on some changes that touched `examples/`. I believe these are the steps causing the issues:

1. Edit any of some of the examples under `examples/` and commit
2. `scripts/ci.sh` will [run `scripts/sync.sh`](https://github.com/google/wasefire/blob/fe57cd1562c3414a8d3649305c75a1935d85b360/scripts/ci.sh#L24). This will [then copy](https://github.com/google/wasefire/blob/fe57cd1562c3414a8d3649305c75a1935d85b360/scripts/sync.sh#L23-L32) over the example in book to the examples in `examples/` and "undo" changes in made in `examples/`
3. Now repo isn't clean so we'll hit the error `Repository is not clean` in [`scripts/publish.sh`](https://github.com/google/wasefire/blob/fe57cd1562c3414a8d3649305c75a1935d85b360/scripts/publish.sh#L22)

I get the point here (we wan't to keep the book and `examples/` in sync), but it took me a while to figure out that some of the scripts were editing the files under me and the error was a little opaque. Maybe we can report error message in `sync.sh` instead?

**Comment by ia0** [comment]
Thanks for the bug report! This is indeed a usability issue for maintainers. I'm fixing it is #445.
